include Catppuccin-Latte.conf
env PATH=$HOME/.local/bin:$HOME/.cargo/bin:/opt/homebrew/bin:/usr/local/bin:$PATH
macos_option_as_alt yes
macos_quit_when_last_window_closed yes
allow_remote_control yes
shell_integration enabled
enabled_layouts splits,stack
hide_window_decorations titlebar-only
clipboard_control write-clipboard read-clipboard
copy_on_select yes
paste_actions quote-urls-at-prompt,confirm-if-large
mouse_hide_wait 3.0
cursor_trail 3
cursor_trail_decay 0.15 0.35
cursor_trail_start_threshold 3
background_opacity 0.75
background_blur 30
scrollback_lines 99999
scrollback_pager_history_size 0
scrollback_pager nvim --cmd 'set eventignore=FileType' +'nnoremap q ZQ' +'call nvim_open_term(0, {})' +'set nomodified nolist' +'$' -

tab_bar_edge top
tab_bar_min_tabs 1
tab_bar_style custom
tab_powerline_style slanted
tab_title_template "{index} {title}"
active_tab_foreground #ffffff
active_tab_background #6b98de
active_tab_font_style bold

map alt+s>v launch --location=vsplit
map alt+s>s launch --location=hsplit
map alt+s>z toggle_layout stack
map alt+s>shift+z detach_window new-tab
map alt+s>i focus_visible_window
map alt+s>q close_window_with_confirmation
map alt+s>t new_tab
map alt+s>n next_tab
map alt+s>p previous_tab
map alt+s>1 goto_tab 1
map alt+s>2 goto_tab 2
map alt+s>3 goto_tab 3
map alt+s>4 goto_tab 4
map alt+s>5 goto_tab 5
map alt+s>tab goto_tab -1
map alt+s>` nth_window -1
map alt+s>h neighboring_window left
map alt+s>l neighboring_window right
map alt+s>k neighboring_window up
map alt+s>j neighboring_window down
map alt+s>shift+h move_window left
map alt+s>shift+l move_window right
map alt+s>shift+k move_window up
map alt+s>shift+j move_window down
map alt+s>ctrl+h resize_window narrower 5
map alt+s>ctrl+l resize_window wider 5
map alt+s>ctrl+k resize_window taller 5
map alt+s>ctrl+j resize_window shorter 5
map alt+s>[ show_scrollback

font_size 15.0
font_family      family=Menlo postscript_name=Menlo-Regular
bold_font        auto
italic_font      auto
bold_italic_font auto
# symbol_map U+23fb-U+23fe,U+2500-U+259f,U+2630,U+2665,U+26a1,U+276c-U+2771,U+2b58,U+e000-U+e00a,U+e0a0-U+e0a2,U+e0a3,U+e0b0-U+e0b3,U+e0b4-U+e0c8,U+e0ca,U+e0cc-U+e0d7,U+e200-U+e2a9,U+e300-U+e3e3,U+e5fa-U+e6b7,U+e700-U+e8ef,U+ea60-U+ec1e,U+ed00-U+efce,U+ee00-U+ee0b,U+f000-U+f2ff,U+f300-U+f381,U+f400-U+f533,U+f500-U+fd46,U+f0001-U+f1af0 Symbols Nerd Font Mono
# Nerd Fonts v3.4.0
symbol_map U+e000-U+e00a,U+e0a0-U+e0a2,U+e0a3,U+e0b0-U+e0b3,U+e0b4-U+e0c8,U+e0ca,U+e0cc-U+e0d7,U+e200-U+e2a9,U+e300-U+e3e3,U+e5fa-U+e6b7,U+e700-U+e8ef,U+ea60-U+ec1e,U+ed00-U+efce,U+f000-U+f2ff,U+f300-U+f381,U+f400-U+f533,U+f0001-U+f1af0 Symbols Nerd Font Mono
